version: 0.2

phases:
  install:
    commands:
      - echo Installing...
  build:
    commands:
      - echo Build started on `date`
      - mkdir -p build
      - cp index.html build/
artifacts:
  files:
    - index.html
  base-directory: build
